name: Build, Test, Push Docker Image and Update GitOps Repo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout application code
      uses: actions/checkout@v3

    - name: Get commit SHA
      id: vars
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t nanil0034/portfolio-app:${{ env.COMMIT_SHA }} .

    - name: Run container to test
      run: |
        docker run -d -p 3000:3000 --name test-portfolio nanil0034/portfolio-app:${{ env.COMMIT_SHA }}
        sleep 10
        docker ps -a
        docker logs test-portfolio
        docker stop test-portfolio
        docker rm test-portfolio

    - name: Push image to Docker Hub
      run: docker push nanil0034/portfolio-app:${{ env.COMMIT_SHA }}

    - name: Clone GitOps repo and update image tag
      env:
        COMMIT_SHA: ${{ env.COMMIT_SHA }}
      run: |
        git config --global user.email "nabilfaruk6@gmail.com"
        git config --global user.name "Istiaque Faroque Nabil"

        git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/Nabil720/K8s_project_1_gitops.git
        cd K8s_project_1_gitops/portfolio-app

        # Update the image tag in deployment.yaml
        sed -i 's|image: nanil0034/portfolio-app:.*|image: nanil0034/portfolio-app:'${COMMIT_SHA}'|' deployment.yaml

        git add deployment.yaml

        # Only commit if something actually changed
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update image tag to ${COMMIT_SHA}"
          git push origin main
        fi
